#!/usr/bin/env bash
# Generate mkcert certs for local HTTPS and Caddyfile.dev from a single domain list.
# One-time: brew install mkcert && mkcert -install
# To add a domain: add one line to scripts/dev-domains.txt, then re-run this script.
set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT_DIR="$REPO_ROOT/dev-certs"
DOMAINS_FILE="$SCRIPT_DIR/dev-domains.txt"
CADDYFILE_DEV="$REPO_ROOT/Caddyfile.dev"
EXAMPLE_FILE="$SCRIPT_DIR/dev-domains.example.txt"

if [[ ! -f "$DOMAINS_FILE" ]]; then
  if [[ -f "$EXAMPLE_FILE" ]]; then
    cp "$EXAMPLE_FILE" "$DOMAINS_FILE"
    echo "Created $DOMAINS_FILE from example. Edit it and re-run if needed."
  else
    echo "No $DOMAINS_FILE. Copy $EXAMPLE_FILE to $DOMAINS_FILE and add your domains."
    exit 1
  fi
fi

# Read domains (skip blank lines and comments)
DOMAINS=()
while IFS= read -r line || [[ -n "$line" ]]; do
  line="${line%%#*}"
  line="${line// /}"
  [[ -z "$line" ]] && continue
  DOMAINS+=( "$line" )
done < "$DOMAINS_FILE"

if [[ ${#DOMAINS[@]} -eq 0 ]]; then
  echo "No domains in $DOMAINS_FILE"
  exit 1
fi

# Single source of truth: write Caddyfile.dev from the domain list (always, even without mkcert)
CADDY_HOSTS="${DOMAINS[*]}"
CADDY_HOSTS="${CADDY_HOSTS// /, }"
cat > "$CADDYFILE_DEV" << EOF
# Dev HTTPS: generated by scripts/gen-dev-certs.sh from scripts/dev-domains.txt
# Edit dev-domains.txt and re-run the script to add/remove domains.
$CADDY_HOSTS {
  tls /certs/cert.pem /certs/key.pem
  reverse_proxy dokploy-traefik:80
}
EOF
echo "Caddyfile.dev updated for: ${DOMAINS[*]}"

mkdir -p "$OUT_DIR"
cd "$OUT_DIR"
if ! command -v mkcert &>/dev/null; then
  echo "mkcert not found. Install with: brew install mkcert && mkcert -install (Caddyfile.dev was still updated.)"
  exit 1
fi
mkcert -install 2>/dev/null || true
mkcert "${DOMAINS[@]}"
# Rename to fixed names (mkcert outputs e.g. relay.local+3.pem, relay.local+3-key.pem)
for f in "${DOMAINS[0]}"+*.pem; do
  [[ -f "$f" ]] || continue
  [[ "$f" == *-key.pem ]] && mv "$f" key.pem || mv "$f" cert.pem
done
echo "Certificates written to $OUT_DIR (cert.pem, key.pem)"